version: '3.8'

services:
  frontend:
    build:
      context: ./front
    container_name: bobapp-front
    ports:
      - "3001:80"  # Mappe le port 3000 de l'hôte sur le port 80 du conteneur (nginx)
    networks:
      - bobapp-network

  backend:
    build:
      context: ./back
    container_name: bobapp-back
    ports:
      - "8080:8080"
    networks:
      - bobapp-network

networks:
  bobapp-network:
    driver: bridge
