name: CD - Docker Push Front & Back

on:
  workflow_run:
    workflows: ["CI - Front & Back"]
    types:
      - completed

jobs:
  docker-build-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Backend
      - name: Build & Push Backend
        run: |
          docker build -t kenchisan/monapp-back:${{ github.ref_name }} backend
          docker push kenchisan/monapp-back:${{ github.ref_name }}
      # Frontend
      - name: Build & Push Frontend
        run: |
          docker build -t kenchisan/monapp-front:${{ github.ref_name }} frontend
          docker push kenchisan/monapp-front:${{ github.ref_name }}
