name: SonarCloud Analysis Split (Backend & Frontend)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write  # nécessaire pour PR decoration

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - run: mvn clean verify jacoco:report

      - name: Upload backend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
        working-directory: front

      - run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
        working-directory: front

      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: angular-coverage
          path: front/coverage/lcov.info

  sonar-backend:
    needs: backend-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Download backend coverage report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: backend-coverage

      - name: Run SonarCloud analysis (Backend)
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        with:
          hostUrl: ${{ secrets.SONAR_HOST_URL }}
          token: ${{ secrets.SONAR_TOKEN_BACK }}
          projectBaseDir: back
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_BACK }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=backend-coverage/jacoco.xml

  sonar-frontend:
    needs: frontend-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download frontend coverage report
        uses: actions/download-artifact@v4
        with:
          name: angular-coverage
          path: front-coverage

      - name: Run SonarCloud analysis (Frontend)
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        with:
          hostUrl: ${{ secrets.SONAR_HOST_URL }}
          token: ${{ secrets.SONAR_TOKEN_FRONT }}
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_FRONT }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.sources=src/app
            -Dsonar.tests=src
            -Dsonar.javascript.lcov.reportPaths=front-coverage/lcov.info