name: SonarQube analysis split (backend & frontend)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # SonarQube needs this to decorate PRs

jobs:
  sonar-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test backend with coverage
        run: |
          cd back
          mvn clean verify jacoco:report

      - name: Analyze backend with SonarQube
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        with:
          host-url: ${{ secrets.SONAR_HOST_URL }}
          token: ${{ secrets.SONAR_TOKEN_BACK }}
          projectBaseDir: back
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_BACK }}
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.exclusions=**/*.spec.ts

  sonar-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and run frontend tests with coverage
        run: |
          cd front
          npm ci
          npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Analyze frontend with SonarQube
        uses: SonarSource/sonarqube-scan-action@v2.0.2
        with:
          host-url: ${{ secrets.SONAR_HOST_URL }}
          token: ${{ secrets.SONAR_TOKEN_FRONT }}
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY_FRONT }}
            -Dsonar.sources=src/app
            -Dsonar.tests=src
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.exclusions=**/*.spec.ts
